export const SUGGESTIONS = [
    "Bike",
    "Breakfast with friends / family",
    "Catch up for Coffee",
    "Cocktail Making",
    "Craft Beer Tasting",
    "Dance like no-one is watching",
    "Donate a Drink",
    "Enjoy live music together",
    "Family Get together",
    "Fly a kite / Throw a frisbie / Kick a ball",
    "Golf / Disc Golf outing",
    "Golf",
    "Group / Social meet up",
    "Hike",
    "Holistic Healing",
    "Kayak",
    "Meet up with friends / family",
    "Online games / cards night",
    "Outdoor Activity",
    "Plant a tree / sow a seed",
    "Pledge a Pint",
    "Prayer Circle or healing circle",
    "Run",
    "Social Club night",
    "Social Gathering",
    "Sports",
    "SUP",
    "Surf some waves",
    "Swim",
    "Table Quiz / Games Night",
    "Team up for tennis",
    "Tennis",
    "Walk",
    "Wine Tasting",
    "Yoga, Meditation, & Well-being",
]

